SELECT
    ID AS INVENTORY_ITEM_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_BRAND,
    PRODUCT_CATEGORY,
    PRODUCT_DEPARTMENT,
    PRODUCT_RETAIL_PRICE,
    COST,
    CREATED_AT,
    SOLD_AT,
    PRODUCT_DISTRIBUTION_CENTER_ID
FROM {{ source('ecommerce_looker', 'INVENTORY_ITEMS') }}