SELECT "PRODUCT_BRAND",
    "PRODUCT_CATEGORY",
    AVG(("PRODUCT_RETAIL_PRICE" - "COST") / NULLIF("PRODUCT_RETAIL_PRICE", 0)) AS "AVG_MARGIN_PERCENT"
FROM {{source('ecommerce_looker', 'INVENTORY_ITEMS')}} AS "inventory_items"
GROUP BY 1, 2
